{ config, lib, pkgs, ... }:
{
	nix.settings.experimental-features = [ "nix-command" "flakes" ];
	nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
		"steam"
                "steamcmd"
		"steam-original"
		"steam-run"
		"nvidia-x11"
		"nvidia-settings"
		"nvidia-persistenced"
                "cuda-merged"
                "cuda_cuobjdump"
                "cuda_gdb"
                "cuda_nvcc"
                "cuda_nvdisasm"
                "cuda_nvprune"
                "cuda_cccl"
                "cuda_cudart"
                "cuda_cupti"
                "cuda_cuxxfilt"
                "cuda_nvml_dev"
                "cuda_nvrtc"
                "cuda_nvtx"
                "cuda_profiler_api"
                "cuda_sanitizer_api"
                "libcublas"
                "libcufft"
                "libcurand"
                "libcusolver"
                "libnvjitlink"
                "libcusparse"
                "libnpp"
	];
}
